-- ============================================================================
-- Product number: a unique 5-character alphanumeric code (base36: 0-9, A-Z)
-- for every product. ~36^5 = 60,466,176 combinations.
-- Auto-generated by default; a vendor may overwrite it with their own code
-- (still validated for uniqueness by the unique index below).
-- Safe to run once in the Supabase SQL editor.
-- ============================================================================

ALTER TABLE products ADD COLUMN IF NOT EXISTS product_no TEXT;

-- Generates a random unused 5-char base36 code (uppercase letters + digits).
CREATE OR REPLACE FUNCTION gen_product_no() RETURNS TEXT
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
  alphabet CONSTANT TEXT := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  code TEXT;
  i INT;
BEGIN
  LOOP
    code := '';
    FOR i IN 1..5 LOOP
      code := code || substr(alphabet, 1 + floor(random() * 36)::int, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM products WHERE product_no = code);
  END LOOP;
  RETURN code;
END;
$$;

-- Backfill existing products one at a time so each new code "sees" the prior
-- ones generated in this same transaction (guarantees no duplicates).
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN SELECT id FROM products WHERE product_no IS NULL LOOP
    UPDATE products SET product_no = gen_product_no() WHERE id = r.id;
  END LOOP;
END $$;

-- Enforce uniqueness, auto-generation on insert, and presence.
CREATE UNIQUE INDEX IF NOT EXISTS products_product_no_key ON products (product_no);
ALTER TABLE products ALTER COLUMN product_no SET DEFAULT gen_product_no();
ALTER TABLE products ALTER COLUMN product_no SET NOT NULL;
