package com.rajkotmarket.erp.dao;

import com.rajkotmarket.erp.db.Database;
import com.rajkotmarket.erp.model.Product;
import com.rajkotmarket.erp.model.ProductVariant;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** CRUD access to the {@code products} table (joined with vendor names). */
public class ProductDao {

    private static final String SELECT_BASE =
            "SELECT p.id, p.product_no, p.vendor_id, v.name AS vendor_name, " +
            "       p.name, p.category, p.description, p.price, p.stock, p.active, " +
            "       (SELECT count(*) FROM product_variants pv WHERE pv.product_id = p.id) AS variant_count " +
            "FROM products p LEFT JOIN vendors v ON v.id = p.vendor_id ";

    /**
     * List products with optional filters.
     * @param search    case-insensitive match on name/category/product_no (null = any)
     * @param vendorId  restrict to one vendor (null = any)
     * @param lowStockThreshold  if >= 0, only rows with stock &lt;= this value
     */
    public List<Product> list(String search, String vendorId, int lowStockThreshold) throws SQLException {
        StringBuilder sql = new StringBuilder(SELECT_BASE).append("WHERE 1=1 ");
        List<Object> args = new ArrayList<>();
        if (search != null && !search.isBlank()) {
            sql.append("AND (p.name ILIKE ? OR p.category ILIKE ? OR p.product_no ILIKE ?) ");
            String like = "%" + search.trim() + "%";
            args.add(like); args.add(like); args.add(like);
        }
        if (vendorId != null) {
            sql.append("AND p.vendor_id = ?::uuid ");
            args.add(vendorId);
        }
        if (lowStockThreshold >= 0) {
            sql.append("AND p.stock <= ? ");
            args.add(lowStockThreshold);
        }
        sql.append("ORDER BY p.name");

        List<Product> out = new ArrayList<>();
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql.toString())) {
            for (int i = 0; i < args.size(); i++) {
                ps.setObject(i + 1, args.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    out.add(map(rs));
                }
            }
        }
        return out;
    }

    /** Insert a new product; product_no is auto-generated by the DB. Returns generated id + product_no. */
    public void insert(Product p) throws SQLException {
        String sql = "INSERT INTO products (vendor_id, name, category, description, price, stock, active) " +
                     "VALUES (?::uuid, ?, ?, ?, ?, ?, ?) RETURNING id, product_no";
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, p.getVendorId());                 // null-safe for uuid
            ps.setString(2, p.getName());
            ps.setString(3, p.getCategory());
            ps.setString(4, p.getDescription());
            ps.setBigDecimal(5, p.getPrice());
            ps.setInt(6, p.getStock());
            ps.setBoolean(7, p.isActive());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    p.setId(rs.getString("id"));
                    p.setProductNo(rs.getString("product_no"));
                }
            }
        }
    }

    /** Update an existing product. Note: stock is NOT changed here — use InventoryService for audited stock moves. */
    public void update(Product p) throws SQLException {
        String sql = "UPDATE products SET vendor_id = ?::uuid, name = ?, category = ?, " +
                     "description = ?, price = ?, active = ?, updated_at = now() WHERE id = ?::uuid";
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, p.getVendorId());
            ps.setString(2, p.getName());
            ps.setString(3, p.getCategory());
            ps.setString(4, p.getDescription());
            ps.setBigDecimal(5, p.getPrice());
            ps.setBoolean(6, p.isActive());
            ps.setObject(7, p.getId());
            ps.executeUpdate();
        }
    }

    /**
     * Per-combination stock rows for a variant-tracked product (size × colour …).
     * Empty when the product keeps a single stock. specs jsonb is pre-formatted
     * server-side into a readable "Key: Value · Key: Value" string.
     */
    public List<ProductVariant> variants(String productId) throws SQLException {
        String sql =
                "SELECT pv.id, pv.specs::text AS specs_json, pv.stock, " +
                "       (SELECT string_agg(key || ': ' || value, ' · ' ORDER BY key) " +
                "          FROM jsonb_each_text(pv.specs)) AS combination " +
                "FROM product_variants pv WHERE pv.product_id = ?::uuid ORDER BY 4";
        List<ProductVariant> out = new ArrayList<>();
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, productId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    out.add(new ProductVariant(rs.getString("id"), rs.getString("combination"),
                            rs.getString("specs_json"), rs.getInt("stock")));
                }
            }
        }
        return out;
    }

    /**
     * The pickable field options of a product's spec template, as an ordered
     * map label → options (e.g. {"Size":[XS,S,M,…], "Colour":[Red,…]}). Used to
     * add new combinations. Empty when the product has no template. The jsonb is
     * unnested in SQL so no JSON parsing is needed in Java.
     */
    public java.util.LinkedHashMap<String, List<String>> templateOptions(String productId) throws SQLException {
        String sql =
                "SELECT f->>'label' AS label, opt AS value, " +
                "       (f_ord - 1) AS field_ord, o_ord AS opt_ord " +
                "FROM products p " +
                "JOIN spec_templates st ON st.id = p.spec_template_id " +
                "JOIN LATERAL jsonb_array_elements(st.fields) WITH ORDINALITY AS fields(f, f_ord) ON true " +
                "JOIN LATERAL jsonb_array_elements_text(f->'options') WITH ORDINALITY AS opts(opt, o_ord) ON true " +
                "WHERE p.id = ?::uuid " +
                "ORDER BY field_ord, opt_ord";
        java.util.LinkedHashMap<String, List<String>> out = new java.util.LinkedHashMap<>();
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, productId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    out.computeIfAbsent(rs.getString("label"), k -> new ArrayList<>()).add(rs.getString("value"));
                }
            }
        }
        return out;
    }

    /**
     * Replace a product's variant rows with the supplied set and keep
     * products.stock as the cached SUM. Audited: a single inventory_log entry
     * records the net product-level change. One transaction (product row locked).
     */
    public void saveVariants(String productId, List<ProductVariant> variants) throws SQLException {
        Connection c = Database.getConnection();
        boolean oldAuto = c.getAutoCommit();
        try {
            c.setAutoCommit(false);

            int before; String name;
            try (PreparedStatement ps = c.prepareStatement(
                    "SELECT name, stock FROM products WHERE id = ?::uuid FOR UPDATE")) {
                ps.setObject(1, productId);
                try (ResultSet rs = ps.executeQuery()) {
                    if (!rs.next()) throw new SQLException("Product not found: " + productId);
                    name = rs.getString("name");
                    before = rs.getInt("stock");
                }
            }

            try (PreparedStatement ps = c.prepareStatement(
                    "DELETE FROM product_variants WHERE product_id = ?::uuid")) {
                ps.setObject(1, productId);
                ps.executeUpdate();
            }

            int total = 0;
            if (!variants.isEmpty()) {
                try (PreparedStatement ps = c.prepareStatement(
                        "INSERT INTO product_variants (product_id, specs, stock) VALUES (?::uuid, ?::jsonb, ?)")) {
                    for (ProductVariant v : variants) {
                        int st = Math.max(0, v.getStock());
                        total += st;
                        ps.setObject(1, productId);
                        ps.setString(2, v.getSpecsJson());
                        ps.setInt(3, st);
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            try (PreparedStatement ps = c.prepareStatement(
                    "UPDATE products SET stock = ?, updated_at = now() WHERE id = ?::uuid")) {
                ps.setInt(1, total);
                ps.setObject(2, productId);
                ps.executeUpdate();
            }

            if (total != before) {
                try (PreparedStatement ps = c.prepareStatement(
                        "INSERT INTO inventory_log (product_id, product_name, change, stock_before, stock_after, reason) " +
                        "VALUES (?::uuid, ?, ?, ?, ?, ?)")) {
                    ps.setObject(1, productId);
                    ps.setString(2, name);
                    ps.setInt(3, total - before);
                    ps.setInt(4, before);
                    ps.setInt(5, total);
                    ps.setString(6, "variant edit (ERP)");
                    ps.executeUpdate();
                }
            }

            c.commit();
        } catch (SQLException e) {
            c.rollback();
            throw e;
        } finally {
            c.setAutoCommit(oldAuto);
            c.close();
        }
    }

    /** Hard-delete a product by id. */
    public void delete(String id) throws SQLException {
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement("DELETE FROM products WHERE id = ?::uuid")) {
            ps.setObject(1, id);
            ps.executeUpdate();
        }
    }

    private static Product map(ResultSet rs) throws SQLException {
        Product p = new Product();
        p.setId(rs.getString("id"));
        p.setProductNo(rs.getString("product_no"));
        p.setVendorId(rs.getString("vendor_id"));
        p.setVendorName(rs.getString("vendor_name"));
        p.setName(rs.getString("name"));
        p.setCategory(rs.getString("category"));
        p.setDescription(rs.getString("description"));
        p.setPrice(rs.getBigDecimal("price"));
        p.setStock(rs.getInt("stock"));
        p.setActive(rs.getBoolean("active"));
        p.setVariantCount(rs.getInt("variant_count"));
        return p;
    }

    /** Quick validity check for a UUID string (used by the UI before querying). */
    public static boolean isUuid(String s) {
        try { UUID.fromString(s); return true; } catch (Exception e) { return false; }
    }
}
