package com.rajkotmarket.erp.dao;

import com.rajkotmarket.erp.db.Database;
import com.rajkotmarket.erp.model.Product;
import com.rajkotmarket.erp.model.ProductVariant;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** CRUD access to the {@code products} table (joined with vendor names). */
public class ProductDao {

    private static final String SELECT_BASE =
            "SELECT p.id, p.product_no, p.vendor_id, v.name AS vendor_name, " +
            "       p.name, p.category, p.description, p.price, p.stock, p.active " +
            "FROM products p LEFT JOIN vendors v ON v.id = p.vendor_id ";

    /**
     * List products with optional filters.
     * @param search    case-insensitive match on name/category/product_no (null = any)
     * @param vendorId  restrict to one vendor (null = any)
     * @param lowStockThreshold  if >= 0, only rows with stock &lt;= this value
     */
    public List<Product> list(String search, String vendorId, int lowStockThreshold) throws SQLException {
        StringBuilder sql = new StringBuilder(SELECT_BASE).append("WHERE 1=1 ");
        List<Object> args = new ArrayList<>();
        if (search != null && !search.isBlank()) {
            sql.append("AND (p.name ILIKE ? OR p.category ILIKE ? OR p.product_no ILIKE ?) ");
            String like = "%" + search.trim() + "%";
            args.add(like); args.add(like); args.add(like);
        }
        if (vendorId != null) {
            sql.append("AND p.vendor_id = ?::uuid ");
            args.add(vendorId);
        }
        if (lowStockThreshold >= 0) {
            sql.append("AND p.stock <= ? ");
            args.add(lowStockThreshold);
        }
        sql.append("ORDER BY p.name");

        List<Product> out = new ArrayList<>();
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql.toString())) {
            for (int i = 0; i < args.size(); i++) {
                ps.setObject(i + 1, args.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    out.add(map(rs));
                }
            }
        }
        return out;
    }

    /** Insert a new product; product_no is auto-generated by the DB. Returns generated id + product_no. */
    public void insert(Product p) throws SQLException {
        String sql = "INSERT INTO products (vendor_id, name, category, description, price, stock, active) " +
                     "VALUES (?::uuid, ?, ?, ?, ?, ?, ?) RETURNING id, product_no";
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, p.getVendorId());                 // null-safe for uuid
            ps.setString(2, p.getName());
            ps.setString(3, p.getCategory());
            ps.setString(4, p.getDescription());
            ps.setBigDecimal(5, p.getPrice());
            ps.setInt(6, p.getStock());
            ps.setBoolean(7, p.isActive());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    p.setId(rs.getString("id"));
                    p.setProductNo(rs.getString("product_no"));
                }
            }
        }
    }

    /** Update an existing product. Note: stock is NOT changed here — use InventoryService for audited stock moves. */
    public void update(Product p) throws SQLException {
        String sql = "UPDATE products SET vendor_id = ?::uuid, name = ?, category = ?, " +
                     "description = ?, price = ?, active = ?, updated_at = now() WHERE id = ?::uuid";
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, p.getVendorId());
            ps.setString(2, p.getName());
            ps.setString(3, p.getCategory());
            ps.setString(4, p.getDescription());
            ps.setBigDecimal(5, p.getPrice());
            ps.setBoolean(6, p.isActive());
            ps.setObject(7, p.getId());
            ps.executeUpdate();
        }
    }

    /**
     * Per-combination stock rows for a variant-tracked product (size × colour …).
     * Empty when the product keeps a single stock. specs jsonb is pre-formatted
     * server-side into a readable "Key: Value · Key: Value" string.
     */
    public List<ProductVariant> variants(String productId) throws SQLException {
        String sql =
                "SELECT (SELECT string_agg(key || ': ' || value, ' · ' ORDER BY key) " +
                "          FROM jsonb_each_text(pv.specs)) AS combination, pv.stock " +
                "FROM product_variants pv WHERE pv.product_id = ?::uuid ORDER BY 1";
        List<ProductVariant> out = new ArrayList<>();
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setObject(1, productId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    out.add(new ProductVariant(rs.getString("combination"), rs.getInt("stock")));
                }
            }
        }
        return out;
    }

    /** Hard-delete a product by id. */
    public void delete(String id) throws SQLException {
        try (Connection c = Database.getConnection();
             PreparedStatement ps = c.prepareStatement("DELETE FROM products WHERE id = ?::uuid")) {
            ps.setObject(1, id);
            ps.executeUpdate();
        }
    }

    private static Product map(ResultSet rs) throws SQLException {
        Product p = new Product();
        p.setId(rs.getString("id"));
        p.setProductNo(rs.getString("product_no"));
        p.setVendorId(rs.getString("vendor_id"));
        p.setVendorName(rs.getString("vendor_name"));
        p.setName(rs.getString("name"));
        p.setCategory(rs.getString("category"));
        p.setDescription(rs.getString("description"));
        p.setPrice(rs.getBigDecimal("price"));
        p.setStock(rs.getInt("stock"));
        p.setActive(rs.getBoolean("active"));
        return p;
    }

    /** Quick validity check for a UUID string (used by the UI before querying). */
    public static boolean isUuid(String s) {
        try { UUID.fromString(s); return true; } catch (Exception e) { return false; }
    }
}
